package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import jakarta.annotation.PostConstruct;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author larissa
 */

@Component
public class CursoEditar extends javax.swing.JFrame {
    private final CursoListar cursoListar;
    private final Long id;
    
    @Autowired
    private CursoIController cursoController;
    
    /**
     * Creates new form CursoEditar
     * @param cursoListar
     * @param id
     */
    public CursoEditar(CursoListar cursoListar, Long id) {
        this.cursoListar = cursoListar;
        this.id = id;
        initComponents();
    }
    
    @PostConstruct
    public void init() {
        carregarCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        lblCodCurso = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodCurso = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        comboStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setText("Status:");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblCodCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodCurso.setText("Código do curso:");
        getContentPane().add(lblCodCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 240, -1));
        getContentPane().add(txtCodCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 240, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 120, 50));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));
        getContentPane().add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        setSize(new java.awt.Dimension(459, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Caarrega as informações do curso a ser editado ao abrir a tela
    private void carregarCurso() {
        Curso curso;
        curso = cursoController.findById(id);
        
        txtNome.setText(curso.getNome());
        txtCodCurso.setText(curso.getCodigoCurso());
        comboStatus.setSelectedItem(curso.isAtivo() ? "ATIVO" : "INATIVO");
    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //Verifica se todos os campos estão preenchidos
        if(txtNome.getText().isEmpty() || txtCodCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null, 
                    "PREENCHA TODOS OS CAMPOS\n", 
                    "ERRO", 
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            //Insere as informações da tela de edição no curso
            Curso curso = new Curso();
            curso.setNome(txtNome.getText());
            curso.setCodigoCurso(txtCodCurso.getText());
            curso.setId(id);

            //Verifica a opção escolhida pelo usuário e coloca o curso como ativo ou inativo
            curso.setAtivo((comboStatus.getSelectedItem() == "ATIVO"));

            //Salva a edição no banco de dados
            cursoController.update(curso);

            //Atualiza a tabela de cursos e fecha a tela de edição
            cursoListar.carregarTabela();
            this.dispose();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel lblCodCurso;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtCodCurso;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
